name: tst_online
channels:
    - conda-forge
dependencies:
    # Base
    - python>=3.7
    - numpy
    # Dataframes
    - pandas
    - geopandas
    # Plotting
    - bqplot
    # Interactive
    - nodejs
    - jupyter
    - jupyterlab
    - notebook
    - ipython
    - ipyleaflet<=0.9.2
    - ipywidgets
    # GEE
    - oauth2client
    - pycrypto
    - pip:
        - appmode
        - google-api-python-client
        - earthengine-api
        - git+git://github.com/USGS-EROS/lcmap-pyccd.git
